#!/usr/bin/env bash
#
# playbook-coverage.sh - Report the waste-playbook coverage matrix
# (waste_category x scope) and its gaps.
#
# Mirror of fcp-coverage.sh for the playbook surface. Reads scope,
# waste_category and confidence from the YAML frontmatter of every playbook
# under skills/cloud-finops/playbooks/ and renders the coverage matrix the
# 2026-08-19 connector field test produced by hand: which category/provider
# cells have playbooks, which are coverage gaps. A zero cell is a decision
# input (write it, or defer it knowingly in docs/ROADMAP.md), not an error.
#
# Output: writes playbook-coverage.md at the repo root and prints a summary
# to stdout. Exit code is 0 if the matrix can be built, 1 if a playbook
# declares a non-canonical scope, waste_category or confidence (typo /
# convention drift) or is missing one of the three facets.
#
# Usage:
#   ./scripts/playbook-coverage.sh           Generate playbook-coverage.md
#   ./scripts/playbook-coverage.sh --check   Fail on non-canonical or missing
#                                            facets, OR if the committed
#                                            playbook-coverage.md differs from
#                                            a fresh render (use in CI). Never
#                                            writes the file, so a check run
#                                            leaves the tree clean.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

CHECK_MODE=""
[[ "${1:-}" == "--check" ]] && CHECK_MODE=1

PB_DIR="skills/cloud-finops/playbooks"
OUT_FILE="playbook-coverage.md"

RENDER_FILE="$(mktemp "${TMPDIR:-/tmp}/playbook-coverage.XXXXXX")"
trap 'rm -f "$RENDER_FILE"' EXIT

# ---- Canonical facet vocabularies -------------------------------------------
# Scopes and categories are the ones the find_playbooks docstring advertises
# and tests/test_conformance.py pins against the bundled data; the taxonomy
# behind the categories is references/finops-waste-detection-playbooks.md
# ("The eight waste categories").
SCOPES=(aws azure gcp cross-cloud)
CATEGORIES=(orphaned idle overprovisioned commitment-mismatch schedule-blindness modernization ai-ml-inefficiency egress)
CONFIDENCES=(obvious likely possible)

declare -A COUNT      # "category|scope" -> n
declare -A CONF_COUNT # confidence -> n
declare -A ROW_TOTAL
declare -A COL_TOTAL
TOTAL=0
ERRORS=0

in_list() {
  local needle="$1"; shift
  local x
  for x in "$@"; do [[ "$x" == "$needle" ]] && return 0; done
  return 1
}

frontmatter_value() {
  # $1 file, $2 key -> value of "key: value" inside the first frontmatter block
  awk -v key="$2" '
    /^---[\r]?$/ { fence++; next }
    fence == 1 && $0 ~ "^" key ":" {
      sub("^" key ":[ ]*", ""); gsub("\r", ""); print; exit
    }
    fence >= 2 { exit }
  ' "$1"
}

for f in "$PB_DIR"/*.md; do
  base="$(basename "$f")"
  [[ "$base" == "README.md" ]] && continue

  scope="$(frontmatter_value "$f" scope)"
  category="$(frontmatter_value "$f" waste_category)"
  confidence="$(frontmatter_value "$f" confidence)"

  for pair in "scope:$scope" "waste_category:$category" "confidence:$confidence"; do
    key="${pair%%:*}"; val="${pair#*:}"
    if [[ -z "$val" ]]; then
      echo "ERROR: $base is missing frontmatter facet '$key'" >&2
      ERRORS=1
    fi
  done
  if [[ -n "$scope" ]] && ! in_list "$scope" "${SCOPES[@]}"; then
    echo "ERROR: $base declares non-canonical scope '$scope'" >&2
    ERRORS=1
  fi
  if [[ -n "$category" ]] && ! in_list "$category" "${CATEGORIES[@]}"; then
    echo "ERROR: $base declares non-canonical waste_category '$category'" >&2
    ERRORS=1
  fi
  if [[ -n "$confidence" ]] && ! in_list "$confidence" "${CONFIDENCES[@]}"; then
    echo "ERROR: $base declares non-canonical confidence '$confidence'" >&2
    ERRORS=1
  fi
  [[ -z "$scope" || -z "$category" || -z "$confidence" ]] && continue

  COUNT["$category|$scope"]=$(( ${COUNT["$category|$scope"]:-0} + 1 ))
  ROW_TOTAL["$category"]=$(( ${ROW_TOTAL["$category"]:-0} + 1 ))
  COL_TOTAL["$scope"]=$(( ${COL_TOTAL["$scope"]:-0} + 1 ))
  CONF_COUNT["$confidence"]=$(( ${CONF_COUNT["$confidence"]:-0} + 1 ))
  TOTAL=$(( TOTAL + 1 ))
done

if [[ "$ERRORS" == "1" ]]; then
  echo "playbook-coverage: frontmatter errors found - fix them before rendering." >&2
  exit 1
fi

# ---- Render ------------------------------------------------------------------
{
  echo "# Waste-playbook coverage matrix"
  echo
  echo "Generated by \`scripts/playbook-coverage.sh\` from the playbook frontmatter -"
  echo "do not edit by hand. CI (\`--check\`) fails when this file drifts from the"
  echo "playbooks, so every coverage change shows up in a PR diff."
  echo
  echo "A zero cell is a coverage gap, not missing data: either a playbook to write"
  echo "or a gap deferred knowingly. The prioritised backlog lives in"
  echo "[docs/ROADMAP.md](docs/ROADMAP.md) and is weighted by expected recoverable"
  echo "spend, not by cell count."
  echo
  header="| waste_category |"
  divider="|---|"
  for s in "${SCOPES[@]}"; do header+=" $s |"; divider+="---|"; done
  header+=" total |"
  divider+="---|"
  echo "$header"
  echo "$divider"
  for c in "${CATEGORIES[@]}"; do
    row="| $c |"
    for s in "${SCOPES[@]}"; do
      n="${COUNT["$c|$s"]:-0}"
      if [[ "$n" == "0" ]]; then row+=" - |"; else row+=" $n |"; fi
    done
    row+=" ${ROW_TOTAL["$c"]:-0} |"
    echo "$row"
  done
  totals="| **total** |"
  for s in "${SCOPES[@]}"; do totals+=" ${COL_TOTAL["$s"]:-0} |"; done
  totals+=" $TOTAL |"
  echo "$totals"
  echo
  echo "## Confidence distribution"
  echo
  echo "| confidence | playbooks |"
  echo "|---|---|"
  for k in "${CONFIDENCES[@]}"; do
    echo "| $k | ${CONF_COUNT["$k"]:-0} |"
  done
  echo
  echo "## Gaps (zero cells)"
  echo
  for c in "${CATEGORIES[@]}"; do
    for s in "${SCOPES[@]}"; do
      if [[ "${COUNT["$c|$s"]:-0}" == "0" ]]; then
        echo "- $c x $s"
      fi
    done
  done
} > "$RENDER_FILE"

if [[ -n "$CHECK_MODE" ]]; then
  if [[ ! -f "$OUT_FILE" ]]; then
    echo "playbook-coverage: $OUT_FILE is missing - run ./scripts/playbook-coverage.sh and commit it." >&2
    exit 1
  fi
  if ! diff -u "$OUT_FILE" "$RENDER_FILE"; then
    echo "playbook-coverage: committed $OUT_FILE is stale - run ./scripts/playbook-coverage.sh and commit the result." >&2
    exit 1
  fi
  echo "OK: $OUT_FILE matches the playbook frontmatter ($TOTAL playbooks)."
else
  mv "$RENDER_FILE" "$OUT_FILE"
  trap - EXIT
  echo "Wrote $OUT_FILE ($TOTAL playbooks across ${#CATEGORIES[@]} categories x ${#SCOPES[@]} scopes)."
fi
